site_name: Lichess Development

repo_url: https://github.com/fitztrev/lichess-docs/
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Dev Environment:
      - lila-gitpod:
          - Setup: lila-gitpod/index.md
          - Usage: lila-gitpod/usage.md
          - Extensions: lila-gitpod/extensions.md
          - Optional Services: lila-gitpod/optional-services.md
          - API Testing: lila-gitpod/api-testing.md
          - Contributing: lila-gitpod/contributing.md
          - Sharing: lila-gitpod/sharing.md
      - lila-docker:
          - Setup: lila-docker/index.md
          - Usage: lila-docker/usage.md
      - Local Setup:
          - Setup: local-setup/index.md
          - Database: local-setup/db.md
          - lila-search: local-setup/lila-search.md
          - Bloop: local-setup/bloop.md
          - intellij: local-setup/intellij.md
  - Development:
      - Working with Lila: development.md
      - Lilaisms: development/lilaisms.md
      - Conventions: development/conventions.md
      - Translations: development/translations.md
      - Frontend: development/frontend.md
      - User Interface: development/ui.md
      - CSRF: development/csrf.md
      - Firefox Multi-Account: development/firefox-multi-account.md
  - Other Resources: other-resources.md

theme:
  name: material
  logo: https://lichess1.org/assets/logo/lichess-white.svg
  font: false
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
